name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Enable Corepack
        run: corepack enable
      - name: Build
        run: |
          pnpm install
          pnpm build
      - name: Restart Service
        run: pm2 restart lc3xt
